### ISSUE TITLE
As a teacher viewing the groups in the Filtered Merged View each group should be assigned a color so that I can tell which points are related by group and they should remain consistent across views to reduce confusion.

### ISSUE THREAD

**Issue by cfblack** [MathNetDev/MathNetClient#11]

**Comment by IsaacNPsmash** [comment]
This appears to be working well in Dev

**Comment by mtstevens** [comment]
Tested in Test and Dev, 09/21/18 @ 1:55pm PDT. Test successful. No errors were encountered. Colors remained as assigned throughout multiple combinations of groups selected to be merged and "object types to be merged."

**Comment by cbradyatinquire** [comment]
Filtered merge view is "deprecated" and the color issue is in another story
