### ISSUE TITLE
As a student receiving an activity from the teacher I should receive the zoom level of the graph.

### ISSUE THREAD

**Issue by cfblack** [MathNetDev/MathNetClient#12]

**Comment by mtstevens** [comment]
Tested in both Test and Dev, 08/24/18 @ 7:55am PDT. Students were successfully sent the zoom level of the graph; however, the scaling of the axes were different between the Activity Designer and the Student View.

In the Student View, axes were scaled depending on the zoom level. For example, a graph that was more zoomed in showed hash marks at every 0.5 units (0, 0.5, 1, 1.5, etc) and a graph that was more zoomed out showed hash marks at every 10 units (0, 10, 20, 30, etc).

In the Activity Designer, the scaling of the axes remained the same regardless of zoom level: hash marks were shown at every 2 units (0, 2, 4, 6, etc).

**Comment by IsaacNPsmash** [comment]
Tested in Dev 9/14/18 @ 8:56 CST.
I found something similar. The axis setting is not sent to the student at all. I changed the axis to polar coordinates and clicked "send view to all" and nothing changed for the student. The student could go in and change the axis themselves, but the teacher's axis does not represent the students'.

**Comment by ghost** [comment]
@mtstevens and @IsaacNPsmash Please test this now. This now should be fixed for all 3 views i.e. Graphics 1,2 and the 3D view. Try setting different zoom levels for each view when sending the activity. Also the axis and grid issues should also be resolved now. Thanks !

**Comment by mtstevens** [comment]
Tested in Test, 10/18/18, 10:40am PDT. Test successful for Graphics2 and 3D Graphics; both the zoom level and axes scaling were successfully sent to students. Graphics1, however, failed in a specific way. The zoom level in admin appears to be sent to students successfully, but it looks as though the axes scaling (and I'm anthropomorphizing here) in Graphics1 want to stay at 2's as much as possible. When I zoom in (in admin), the hash marks get really spread out and the scaling refuses to be adjusted (it stays with even numbers). When I zoom out, the hash marks get really close to each other and the axes look crowded with even numbers... until I zoom out far enough. At some threshold, the axes scaling changes, but by specific intervals: from 2's to 4's, then to 10's, 20's, 40's, 100's (I didn't zoom out past that). Furthermore, the scaling of the x-axis didn't always match the scaling of the y-axis, but the scaling of both axes followed the specific interval rule stated earlier. To contrast this phenomenon with Graphics2 and 3D Graphics, the axes scaling 'self-adjusted' to various intervals when zooming in and out.

**Comment by cbradyatinquire** [comment]
now axis settings are sent to the student . closing
