### ISSUE TITLE
As a teacher using the admin view when I view  the class view after pushing an activity and I click the Merge Checked Views button I should not see a GeoGebra processing of command errors. 

### ISSUE THREAD

**Issue by cfblack** [MathNetDev/MathNetClient#13]
Related to renaming of similar Geogebra object files across groups.

**Comment by IsaacNPsmash** [comment]
Tested Dev 9/14/18 @ 8:58.
This seems to work well, i.e. no command errors, and points get assigned different names based on groups.

**Comment by cbradyatinquire** [comment]
fixed in the long past
