### ISSUE TITLE
Send the toolbars from the Activity Designer for any perspective

### ISSUE THREAD

**Issue by cbradyatinquire** [MathNetDev/MathNetClient#18]
Whatever toolbars are displayed in the Activity Designer, these should go to the student.

**Comment by mtstevens** [comment]
Tested in Test and Dev, 09/14/18 @ 12:30pm PDT. The following are the scenarios tested, in the order that they were tested (in case that provides any insight), along with the outcome:

1) Sent the default Algebra & Graphics 1 views. Test successful: Toolbar for Graphics 1 was sent fine.
2) Sent only the Spreadsheet view. Test successful: Toolbar for Spreadsheet was sent fine.
3) Sent only the 3D Graphics view. TEST FAILED: Students instead received the default view (Algebra & Graphics 1) with the default toolbar (Graphics 1).
4a) Sent the Graphics 1 & Spreadsheet views, with the Spreadsheet view as the 'active' pane. Test successful: Students received both views, with the Spreadsheet toolbar as the 'active' toolbar.
4b) Sent the same views as Item 4a above, but with the Graphics 1 view as the 'active' pane. TEST FAILED: Students received the same information as in Item 4a above (both views, with Spreadsheet toolbar 'active').
5a) Sent the 3D Graphics & Graphics 1 views, with 3D Graphics as 'active.' TEST FAILED: Students received only the Graphics 1 view, along with its associated toolbar.
5b) Sent the same views as Item 5a above, but with Graphics 1 as 'active.' TEST FAILED: Students received the same information as in Item 5a above (only Graphics 1 and its associated toolbar).
6a) Sent the 3D Graphics & Spreadsheet views, with Spreadsheet as 'active' pane. TEST FAILED: Students only received the Spreadsheet view with its associated toolbar.
6b) Sent the same information as Item 6a above, but with 3D Graphics as 'active.' TEST FAILED: Students received the same information as Item 6a above (only Spreadsheet and its associated toolbar).

Concluding remarks:
It seems that 3D Graphics is still 'broken' when it comes to being sent to students, so all scenarios involving 3D Graphics failed. It also seems that Spreadsheet supercedes Graphics 1 as the 'dominant' view/toolbar, regardless of what is active in the Activity Designer at the time the views are sent to students.

**Comment by cbradyatinquire** [comment]
Closed modulo 3d view (another issue)
