### ISSUE TITLE
Text boxes appearing in 'Normal' Merged View and Filtered Merged View are relocated to the origin

### ISSUE THREAD

**Issue by mtstevens** [MathNetDev/MathNetClient#22]
Regardless of where the text boxes are initially placed, when merging views, the text boxes get relocated to the origin and are lined up along the x-axis. This occurs on all three server levels (ClassNet, MathNetTest, MathNetDev).

In Filtered Merged View (MathNetTest and MathNetDev only), this also occurs regardless of which boxes are checked/unchecked under "Select Object Types to be Merged." In other words, text boxes _always_ appear, at the origin, in Filtered Merged View.

**Comment by ghost** [comment]
@mtstevens This issue should be fixed on the normal merged view now on the test environment. Please test and let me know. If needed we can try and make the same change for the filtered merged view as well although I feel like since now I've also fixed the renaming issue we had earlier, we might not really need the filtered merged view anymore.

**Comment by mtstevens** [comment]
Tested in Test, 10/4/18 @ 9:50am PDT. Test successful. When normal merged view is used, text boxes remained where initially positioned.

**Comment by ghost** [comment]
@mtstevens Thanks for your feedback ! This issue should also be resolved on the Filtered merged view on test now. Note that textboxes will always appear on the filtered merged view irrespective of the types of objects selected on this view. Thanks.

**Comment by mtstevens** [comment]
Tested in Test, 10/10/18 @ 10:40am PDT. Test conditionally successful.

Text boxes appear in Filtered Merged View where initially placed; however, all other elements appear (points, lines, etc.) regardless of whatever is checked or unchecked in "Select Object Types to Be Merged."

**Comment by ghost** [comment]
Since we're working towards phasing out the Filtered Merged View, not working on fixing the issue @mtstevens mentioned in the above comment. If needed we can open a new issue for this.
