### ISSUE TITLE
"Leave Class" button in admin account is not functioning

### ISSUE THREAD

**Issue by mtstevens** [MathNetDev/MathNetClient#23]
Tested on all three server levels (ClassNet, MathNetTest, MathNetDev), 8/16/18 @ 5:50pm PDT. When logged in as admin, clicking the "Leave Class" button under the 'Admin' tab does not do anything. Refreshing the browser brings me back to the screen that says "Click To Join A Class" at the top, with the red "Logout" button at the bottom.

**Comment by mtstevens** [comment]
Tested on all three server levels, 09/14/18 @ 12:40pm PDT. Test failed. Button still does not function as intended.

**Comment by mtstevens** [comment]
Tested on Test and Dev, 10/4/18 @ 11:45a PDT. Test successful. "Leave Class" seems to work as intended now (it brings me back to the initial screen where I can "Logout" properly).

**Comment by ghost** [comment]
Not sure if this issue is still there. @mtstevens could you please retest or let me know the status on this so we can resolve it. Thanks.

**Comment by mtstevens** [comment]
Retested on all three servers, 10/18/18, 11:15am PDT. "Leave Class" works on Test and Dev servers, but does not work on Classnet server.

**Comment by ghost** [comment]
@mtstevens Thank you for testing. I've fixed it on Classnet now. Please check and let me know. Thanks.

**Comment by mtstevens** [comment]
Tested on Classnet, 10/30/18 @ 7:45am PDT. Test successful. "Leave Class" now works.

**Comment by ghost** [comment]
Thanks @mtstevens !
