### ISSUE TITLE
Solve the "rubber-banding" problem that happens between students

### ISSUE THREAD

**Issue by DinoPuppo** [MathNetDev/MathNetClient#25]

**Comment by DinoPuppo** [comment]
Currently working on making it more fluid

**Comment by mtstevens** [comment]
Tested in Test and Dev, 09/20/18 @ 2:15pm PDT. Test successful with 2 students grouped together. Points defining a line were successfully claimed, moved, and placed 'simultaneously' without any rubber-banding occurring.

**Comment by cbradyatinquire** [comment]
We can close this if we open a different issue for the 3-person problem.

**Comment by cbradyatinquire** [comment]
close = this is fixed by kevin's solution (new issues created)
