### ISSUE TITLE
Change the labels for the button keyboard

### ISSUE THREAD

**Issue by DinoPuppo** [MathNetDev/MathNetClient#26]
Also test the I, J, K, L keys

**Comment by mtstevens** [comment]
Tested in Test and Dev, 09/14/18 @ 12:50pm PDT. Arrow keys work, but IJKL keys are unresponsive. Additionally, the Step Size slider doesn't work for the arrow keys (i.e., points still move with a step size of 1 regardless of slider position), but it _does_ work when I click the actual movement buttons with my mouse (e.g., clicking "up(I)" with my mouse moves a point with a step size consistent with the slider).

**Comment by DinoPuppo** [comment]
The I, J, K, L keys only work after a click is made outside of the applet

**Comment by ghost** [comment]
Seems to be completed 26 days back so closing
