### ISSUE TITLE
Circles do not work in either Dev or Test

### ISSUE THREAD

**Issue by IsaacNPsmash** [MathNetDev/MathNetClient#29]
Tested Dev and Test 9/14/18 @ 9:45
Sent View: Three points and a circle
Groups: 1 group with 3 students, each student controlling one point.
Bug: After the third student clicks and moves their point, the circle in the other two students' view disappears becoming "undefined." The third students circle similarly disappears after one of the other students moves their point. Sometimes this happens when the second student clicks and moves their point, the circle disappears for other students.

**Comment by mtstevens** [comment]
Tested in Test and Dev, 09/14/18 @ 1:45pm PDT. To add nuance to Isaac's story above...

Student 1 claims and moves a point. This change is reflected on the screens for Students 2 and 3, with the circle defined and visible for all three students. When S2 claims and moves an unassigned point, however, the circle becomes undefined (and disappears) only for S1 and S2. S3 still sees the circle, but the Algebra pane is behaving as if the circle's equation is constantly being updated (although nothing is being clicked or dragged during this behavior). When S3 claims and moves the remaining unassigned point, then the circle becomes undefined (and disappears) on S3's screen as well.

**Comment by cbradyatinquire** [comment]
issue was not observed on 1/16
