### ISSUE TITLE
Reorder and Rename Activity Designer and User Customizations within Designer

### ISSUE THREAD

**Issue by cbradyatinquire** [MathNetDev/MathNetClient#32]
(and rename:
Activity Designer -> CREATE

User Customization -> CUSTOMIZE

**Comment by mtstevens** [comment]
Tested in Test, 10/4/18 @ 9:50 PDT. Test successful. CREATE (formerly Activity Designer) is listed first and CUSTOMIZE (formerly User Customizations) is listed under CREATE.

**Comment by ghost** [comment]
Closing since tested.
