### ISSUE TITLE
Add the Live option to the Normal Merge View in Class View

### ISSUE THREAD

**Issue by cbradyatinquire** [MathNetDev/MathNetClient#39]

**Comment by ghost** [comment]
I think the live toggle and updating might be a little slower on the merged view due to the renaming logic I had to use. Please test and let me know. Thanks.

**Comment by mtstevens** [comment]
Tested in Test, 10/17/18 @ 11:05am PDT. Test successful.

Elements tested: points, lines, polygons, circles, conics, parallel lines. All elements seemed to update without any apparent lag when "live" was turned on, and nothing updated when "live" was turned off.

**Comment by ghost** [comment]
Thank you @mtstevens
